name: RPG_Game_SDL_C CI
os: Visual Studio 2019
platform: x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

  steps:
  - mkdir build_msbuild
  - cd build_msbuild
  - cmake -G "Visual Studio 15 2019 Win64" ..
  - msbuild RPG_LOR_Game.vcxproj
  - ctest
  - cd ..
