name: my-workflow-name

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && find . -name “libgtest*.a”
    - uses: actions/checkout@v1
    - name: Update Environment
      run: sudo apt-get update
    - name: Configure Environment
      run: sudo apt install libsdl2-dev && sudo apt install libsdl2-image-dev && sudo apt install cmak
    - name: Cmake prepare
      run: cmake CMakeLists.txt
    - name: Make
      run: make
