name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Configure Environment
          run: sudo apt install libsdl2-dev && sudo apt install libsdl2-image-dev
        - name: Make
          run: make -C "RPG_LOR_Game"
