on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

image: gcc

before_script:
    -apt-get update && apt-get -y install cake


myapp:
    stage: build
    script:
        - cd RPG_LOR_Game
        - mkdir build
        - cd build
        - cake ..
        - make
