name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - name: Update Environment
          run: sudo apt-get update
        - name: Configure Environment
          run: sudo apt install libsdl2-dev && sudo apt install libsdl2-image-dev && sudo apt install cmake
        
        - name: Cmake prepare
          run: cmake CMakeLists.txt
        - name: Make
          run: make
