name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: Update Environment
      run: sudo apt-get update
    - name: Configure Environment
      run: sudo apt install libsdl2-dev && sudo apt install libsdl2-image-dev && sudo apt install cmake
    - name: Cmake prepare
      run: cmake CMakeLists.txt
    - name: Make
      run: make
  
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cmake prepare
      shell: pwsh
      run: cmake CMakeLists.txt
    - name: build
      shell: pwsh
      run: make
