on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

image: gcc

jobs:
    build:
        runs-on: linux-latest

    steps:
        - apt-get update 
        - apt-get -y install cmake
        - cd RPG_LOR_Game
        - mkdir build
        - cd build
        - cmake ..
        - make
