name: RPG_Game_SDL_C CI
platform: x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: Visual Studio 2019

    steps:
    - mkdir build_msbuild
    - cd build_msbuild
    - cmake -G "Visual Studio 15 2019 Win64" ..
    - msbuild RPG_LOR_Game.sln
    - ctest
    - cd ..
