name: RPG_Game_SDL_C CI
os: Visual Studio 2019
platform: x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

build:
  - cd RPG_LOR_Game
  - mkdir build_msbuild
  - cd build_msbuild
  - cmake -G "Visual Studio 17" ..
  - msbuild RPG_LOR_Game.vcxproj
  - ctest
  - cd ..
