name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && ls && pwd && ls lib
    - uses: actions/checkout@v1
    - name: Update Environment
      run: sudo apt-get update
    - name: Configure Environment
      run: sudo apt install libsdl2-dev && sudo apt install libsdl2-image-dev && sudo apt install cmake
    - name: Cmake prepare
      run: cmake CMakeLists.txt
    - name: Make
      run: make
